DROP TABLE ABC;
DROP TABLE OBJ;
DROP TABLE STUDENT;
CREATE TABLE STUDENT(
    STU_CODE NUMBER(5) NOT NULL,
    STU_NAME VARCHAR2(20 BYTE) NOT NULL,
    STU_AGE NUMBER(2) NOT NULL,
    CONSTRAINT PK_STUDENT PRIMARY KEY(STU_CODE)
);
CREATE TABLE OBJ(
    OBJ_CODE VARCHAR2(2) NOT NULL,
    OBJ_NAME VARCHAR2(20 BYTE) NOT NULL,
    OBJ_TEAC VARCHAR2(20 BYTE) NOT NULL,
    CONSTRAINT PK_OBJ PRIMARY KEY(OBJ_CODE)
);
CREATE TABLE ABC(
    ABC_CODE NUMBER(2) NOT NULL,
    STU_CODE NUMBER(5) NOT NULL,
    OBJ_CODE VARCHAR2(2) NOT NULL,
    CONSTRAINT PK_ABC PRIMARY KEY(ABC_CODE),
    CONSTRAINT FK_ABC_STUDENT FOREIGN KEY(STU_CODE) REFERENCES STUDENT(STU_CODE),
    CONSTRAINT FK_ABC_OBJ FOREIGN KEY(OBJ_CODE) REFERENCES OBJ(OBJ_CODE)
);