-- 테이블 삭제
DROP TABLE DEPARTMENT CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE PJT CASCADE CONSTRAINTS;
DROP TABLE PROCEEDING CASCADE CONSTRAINTS;

-- 부서 테이블 생성
CREATE TABLE DEPARTMENT(
    DEPT_NO VARCHAR2(15 BYTE) NOT NULL,
    DEPT_NAME VARCHAR2(30 BYTE) NULL,
    DEPT_LOCATION VARCHAR2(50 BYTE) NULL,
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY(DEPT_NO)
);

-- 사원 테이블 생성
CREATE TABLE EMPLOYEE(
    EMP_NO NUMBER NOT NULL,
    DEPT_NO VARCHAR2(15 BYTE) NULL,
    EMP_POSITION CHAR(15 BYTE) NULL,
    EMP_NAME VARCHAR2(15 BYTE) NULL,
    EMP_HIRE_DATE DATE NULL,
    EMP_SALARY NUMBER NULL,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY(EMP_NO),
    CONSTRAINT FK_EMPLOYEE_DEPARTMET FOREIGN KEY(DEPT_NO) REFERENCES DEPARTMENT(DEPT_NO)
);

-- 프로젝트 테이블 생성
CREATE TABLE PJT(
    PJT_NO NUMBER NOT NULL,
    PJT_NAME VARCHAR2(30 BYTE) NULL,
    PJT_BEGIN_DATE DATE NULL,
    PJT_END_DATE DATE NULL,
    CONSTRAINT PK_PJT PRIMARY KEY(PJT_NO)
);

-- 프로젝트진행 테이블 생성
CREATE TABLE PROCEEDING(
    PCD_NO NUMBER NOT NULL,
    EMP_NO NUMBER NULL,
    PJT_NO NUMBER NULL,
    PJT_STATE NUMBER NOT NULL,
    CONSTRAINT PK_PROCEEDING PRIMARY KEY(PCD_NO),
    CONSTRAINT FK_PROCEEDING_EMPLOYEE FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(EMP_NO),
    CONSTRAINT FK_PROCEEDING_PJT FOREIGN KEY(PJT_NO) REFERENCES PJT(PJT_NO)
);
