CREATE TABLE STUDENT(
    STU_NO NUMBER(5) NOT NULL,
    STU_NAME VARCHAR2(15 BYTE) NOT NULL,
    STU_ADDR VARCHAR2(50 BYTE) NULL,
    STU_GRADE NUMBER(1) NOT NULL,
    PRO_NO NUMBER(5) NOT NULL
);

CREATE TABLE PROFESSOR(
    PRO_NO NUMBER(5) NOT NULL,
    PRO_NAME VARCHAR2(15 BYTE) NOT NULL,
    PRO_OBJ VARCHAR2(20 BYTE) NOT NULL
);

CREATE TABLE LECTURE(
    LEC_NO NUMBER(5) NOT NULL,
    PRO_NO NUMBER(5) NOT NULL,
    ENR_NO NUMBER(5) NOT NULL,
    LEC_NAME VARCHAR2(20 BYTE) NOT NULL,
    LEC_SPACE VARCHAR2(10 BYTE)NOT NULL
);

CREATE TABLE ENROLL(
    ENR_NO NUMBER(5) NOT NULL,
    STU_NO NUMBER(5) NOT NULL,
    COU_NO NUMBER(5) NOT NULL,
    ENR_DATE DATE NULL
);

CREATE TABLE COURSE(
    COU_NO NUMBER(5) NOT NULL,
    COU_NAME VARCHAR2(20 BYTE) NOT NULL,
    COU_SCORE NUMBER(5) NOT NULL
);

ALTER TABLE STUDENT 
    ADD CONSTRAINT PK_STUDENT PRIMARY KEY(STU_NO);
ALTER TABLE PROFESSOR 
    ADD CONSTRAINT PK_PROFESSOR PRIMARY KEY(PRO_NO);
ALTER TABLE LECTURE 
    ADD CONSTRAINT PK_LECTURE PRIMARY KEY(LEC_NO);
ALTER TABLE ENROLL 
    ADD CONSTRAINT PK_ENROLL PRIMARY KEY(ENR_NO);
ALTER TABLE COURSE 
    ADD CONSTRAINT PK_COURSE PRIMARY KEY(COU_NO);
    
ALTER TABLE STUDENT 
    ADD CONSTRAINT FK_STUDENT_PROFESSOR FOREIGN KEY(PRO_NO) 
        REFERENCES PROFESSOR(PRO_NO);
ALTER TABLE LECTURE 
    ADD CONSTRAINT FK_LECTURE_PROFESSOR FOREIGN KEY(PRO_NO) 
        REFERENCES PROFESSOR(PRO_NO);
ALTER TABLE LECTURE 
    ADD CONSTRAINT FK_LECTURE_ENROLL FOREIGN KEY(ENR_NO) 
        REFERENCES ENROLL(ENR_NO);
ALTER TABLE ENROLL 
    ADD CONSTRAINT FK_ENROLL_STUDENT FOREIGN KEY(STU_NO) 
        REFERENCES STUDENT(STU_NO);
ALTER TABLE ENROLL 
    ADD CONSTRAINT FK_ENROLL_COURSE FOREIGN KEY(COU_NO) 
        REFERENCES COURSE(COU_NO);

