DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ NOCACHE;

DROP TABLE BOARD;
CREATE TABLE BOARD (
    BOARD_NO NUMBER             NOT NULL,
    TITLE   VARCHAR2(1000 BYTE) NOT NULL,
    CONTENT VARCHAR2(4000 BYTE),    -- 에디터 사용(더 큰 크기가 필요하면 CLOB 타입을 
    WRITER  VARCHAR2(100 BYTE)  NOT NULL,
    CREATE_DATE VARCHAR2(10 BYTE),
    MODIFY_DATE VARCHAR2(10 BYTE),
    CONSTRAINT PK_BOARD PRIMARY KEY(BOARD_NO)
);
INSERT
	INTO BOARD
		(BOARD_NO, TITLE, CONTENT, WRITER, CREATE_DATE)
	VALUES
		(BOARD_SEQ.NEXTVAL, '제목', '내용', '이정행', SYSDATE);
COMMIT;