DROP SEQUENCE GEUL_SEQ;
CREATE SEQUENCE GEUL_SEQ NOCACHE;

DROP TABLE GEUL;
CREATE TABLE GEUL (
	GEUL_NO NUMBER NOT NULL,
	USERS VARCHAR2(20 BYTE) NOT NULL,
	TITLE VARCHAR2(100 BYTE) NOT NULL,
	CONTENT VARCHAR2(500 BYTE),
	CREATE_DATE DATE,
	CONSTRAINT PK_GEUL PRIMARY KEY(GEUL_NO)
);

INSERT INTO GEUL VALUES(GEUL_SEQ.NEXTVAL, '이정행', '제목테스트', '내용테스트', SYSDATE);
COMMIT;